# Model Training

In [23]:
import pandas as pd

In [24]:
df=pd.read_csv(r"D:\Yash\projects\DiamondPricePrediction\notebook\data\gemstone.csv")
df.head()

,Unnamed: 0,carat,cut,color,clarity,depth,table,x,y,z,price
0,1,0.30,Ideal,E,SI1,62.1,58.0,4.27,4.29,2.66,499
1,2,0.33,Premium,G,IF,60.8,58.0,4.42,4.46,2.70,984
2,3,0.90,Very Good,E,VVS2,62.2,60.0,6.04,6.12,3.78,6289
3,4,0.42,Ideal,F,VS1,61.6,56.0,4.82,4.80,2.96,1082
4,5,0.31,Ideal,F,VVS1,60.4,59.0,4.35,4.43,2.65,779

In [25]:
df.columns

Index(['Unnamed: 0', 'carat', 'cut', 'color', 'clarity', 'depth', 'table', 'x',
       'y', 'z', 'price'],
      dtype='object')

In [26]:
df.drop(labels=['Unnamed: 0'],axis=1)

       carat        cut color clarity  depth  table     x     y     z  price
0       0.30      Ideal     E     SI1   62.1   58.0  4.27  4.29  2.66    499
1       0.33    Premium     G      IF   60.8   58.0  4.42  4.46  2.70    984
2       0.90  Very Good     E    VVS2   62.2   60.0  6.04  6.12  3.78   6289
3       0.42      Ideal     F     VS1   61.6   56.0  4.82  4.80  2.96   1082
4       0.31      Ideal     F    VVS1   60.4   59.0  4.35  4.43  2.65    779
...      ...        ...   ...     ...    ...    ...   ...   ...   ...    ...
26962   1.11    Premium     G     SI1   62.3   58.0  6.61  6.52  4.09   5408
26963   0.33      Ideal     H      IF   61.9   55.0  4.44  4.42  2.74   1114
26964   0.51    Premium     E     VS2   61.7   58.0  5.12  5.15  3.17   1656
26965   0.27  Very Good     F    VVS2   61.8   56.0  4.19  4.20  2.60    682
26966   1.25    Premium     J     SI1   62.0   58.0  6.90  6.88  4.27   5166

[26967 rows x 10 columns]

In [27]:
#df.drop(df.columns[df.columns.str.contains('Unnamed')],axis=1,inplace=True)

In [28]:
df.head()

,Unnamed: 0,carat,cut,color,clarity,depth,table,x,y,z,price
0,1,0.30,Ideal,E,SI1,62.1,58.0,4.27,4.29,2.66,499
1,2,0.33,Premium,G,IF,60.8,58.0,4.42,4.46,2.70,984
2,3,0.90,Very Good,E,VVS2,62.2,60.0,6.04,6.12,3.78,6289
3,4,0.42,Ideal,F,VS1,61.6,56.0,4.82,4.80,2.96,1082
4,5,0.31,Ideal,F,VVS1,60.4,59.0,4.35,4.43,2.65,779

In [29]:
#Independent and dependent Features     
X=df.drop('price',axis=1)
Y=df[['price']]

In [30]:
X

,Unnamed: 0,carat,cut,color,clarity,depth,table,x,y,z
0,1,0.30,Ideal,E,SI1,62.1,58.0,4.27,4.29,2.66
1,2,0.33,Premium,G,IF,60.8,58.0,4.42,4.46,2.70
2,3,0.90,Very Good,E,VVS2,62.2,60.0,6.04,6.12,3.78
3,4,0.42,Ideal,F,VS1,61.6,56.0,4.82,4.80,2.96
4,5,0.31,Ideal,F,VVS1,60.4,59.0,4.35,4.43,2.65
...,...,...,...,...,...,...,...,...,...,...
26962,26963,1.11,Premium,G,SI1,62.3,58.0,6.61,6.52,4.09
26963,26964,0.33,Ideal,H,IF,61.9,55.0,4.44,4.42,2.74
26964,26965,0.51,Premium,E,VS2,61.7,58.0,5.12,5.15,3.17
26965,26966,0.27,Very Good,F,VVS2,61.8,56.0,4.19,4.20,2.60
26966,26967,1.25,Premium,J,SI1,62.0,58.0,6.90,6.88,4.27

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26967 entries, 0 to 26966
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  26967 non-null  int64
 1   carat       26967 non-null  float64
 2   cut         26967 non-null  object
 3   color       26967 non-null  object
 4   clarity     26967 non-null  object
 5   depth       26270 non-null  float64
 6   table       26967 non-null  float64
 7   x           26967 non-null  float64
 8   y           26967 non-null  float64
 9   z           26967 non-null  float64
 10  price       26967 non-null  int64
dtypes: float64(6), int64(2), object(3)
memory usage: 2.3+ MB

In [32]:
#Segrating numeriacl and categorical columns

numerical_cols=X.select_dtypes(exclude='object').columns
categorical_cols=X.select_dtypes(include='object').columns

In [33]:
#Define the custom ranking for each ordinal variable'

cut_col=['Fair', 'Good', 'Very Good','Premium','Ideal']
clarity_col=['I1','SI2',"SI1",'VS2','VS1','VVS2','VVS1','IF']
color_col=['D','E','F','G','H','I','J']

In [34]:
from sklearn.impute import SimpleImputer  ## for Handaling misssing values
from sklearn.preprocessing import StandardScaler ## Feature scaleing
from sklearn.preprocessing import OrdinalEncoder #Ordinal Encoding

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [35]:
## Numerical Pipeline
num_pipeline=Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy='median')),
        ('scaler',StandardScaler())
    ]
)


## Categorical Pipeline
cat_pipeline=Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy='most_frequent')),
        ('ordinalencoder',OrdinalEncoder(categories=[cut_col,color_col,clarity_col])),
        ('standardscaler',StandardScaler())
    ]
)

## Preprocessing// combining both piplines

preprocessor=ColumnTransformer([
    ('num_pipeline',num_pipeline,numerical_cols),
    ('cat_pipeline',cat_pipeline,categorical_cols)
])

In [36]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(X,Y,random_state=30,test_size=0.30)

In [37]:
x_train=pd.DataFrame(preprocessor.fit_transform(x_train),columns=preprocessor.get_feature_names_out())
x_test=pd.DataFrame(preprocessor.transform(x_test),columns=preprocessor.get_feature_names_out())

In [38]:
x_train.head()

,num_pipeline__Unnamed: 0,num_pipeline__carat,num_pipeline__depth,num_pipeline__table,num_pipeline__x,num_pipeline__y,num_pipeline__z,cat_pipeline__cut,cat_pipeline__color,cat_pipeline__clarity
0,-1.144668,0.561674,0.318936,-0.651005,0.704838,0.692859,0.723432,0.983583,0.226283,0.576148
1,-1.046522,-0.604087,-0.397691,1.589878,-0.533052,-0.486169,-0.533329,-0.812066,-0.945547,-0.639724
2,1.203004,-0.520818,-0.254365,-1.099182,-0.409263,-0.376688,-0.410385,0.983583,0.812198,-1.247659
3,-1.390742,-0.999613,0.247274,-1.099182,-1.178523,-1.134635,-1.107067,0.983583,0.812198,0.576148
4,0.665320,0.228599,0.963901,-0.651005,0.413049,0.330729,0.477544,-0.812066,0.812198,-0.031788

### Model Training

In [39]:
## Model Training
from sklearn.linear_model import LinearRegression,ElasticNet,Lasso,Ridge
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [40]:
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [41]:
regressor.coef_

array([[ 2.89104647e+00,  4.99001155e+03, -1.17558769e+02,
        -7.15658110e+01, -8.11774623e+02,  2.37495509e+01,
        -2.28621581e+01,  1.28661710e+02, -5.51423820e+02,
         8.35489939e+02]])

In [42]:
regressor.intercept_

array([3944.254662])

In [43]:
import numpy as np
def evaluate_model(true,predicted):
    r2_square=r2_score(true,predicted)
    mae=mean_absolute_error(true,predicted)
    mse=mean_squared_error(true,predicted)
    rmse=np.sqrt(mean_squared_error(true,predicted))
    
    return r2_square,mae,rmse

In [44]:
"""##Train multiple model
 ## Model evaluation"""

models={
        'LinearRegression':LinearRegression(),
        'Lasso':Lasso(),
        'Ridge':Ridge(),
        'ElasticNet':ElasticNet()
} 
 
train_model_list=[]
model_list=[]
r2_list=[] 


for i in range(len(list(models))):
        '##Selecting one model'
        model=list(models.values())[i]
        
        '##training'
        model.fit(x_train,y_train)
        
        '## Predicting'
        y_pred=model.predict(x_test)
        
        '# Model predication'
        r2_square,mae,rmse=evaluate_model(y_test,y_pred)
        
        print(list(models.values())[i])
        model_list.append(list(models.values())[i])
        
        print("Model training Performance")
        print('RMSE',rmse)
        print('MAE',mae)
        print('R2_score',r2_square*100)
        
        
        r2_list.append(r2_square)
        
        print('='*35)
        print('\n')

LinearRegression()
Model training Performance
RMSE 1179.6539753678549
MAE 813.7760250438939
R2_score 91.4416024452861
===================================


Lasso()
Model training Performance
RMSE 1180.840294670093
MAE 815.3980384078773
R2_score 91.42438028080903
===================================


Ridge()
Model training Performance
RMSE 1179.832504046762
MAE 814.0427962369467
R2_score 91.43901179572534
===================================


ElasticNet()
Model training Performance
RMSE 1629.2684047377663
MAE 1079.239997796474
R2_score 83.67442612334273
===================================